List<Map<String, dynamic>> obatList = [
  {
    'judul': 'Amlodipine Besylate 10mg',
    'harga': 'Rp 12.000',
    'foto': 'assets/images/amlodipine.webp',
    'kategori': 'Resep',
    'deskripsi': 'Amlodipine adalah obat golongan antagonis kalsium yang digunakan untuk mengatasi tekanan darah tinggi (hipertensi) dan meredakan nyeri dada (angina). Obat ini bekerja dengan melemaskan dinding pembuluh darah sehingga aliran darah menjadi lebih lancar.',
  },
  {
    'judul': 'Amoxicillin Trihydrate 500mg',
    'harga': 'Rp 15.500',
    'foto': 'assets/images/amoxicillin.webp',
    'kategori': 'Resep',
    'deskripsi': 'Amoxicillin adalah obat antibiotik untuk mengatasi berbagai infeksi bakteri, seperti infeksi saluran pernapasan, saluran kemih, dan infeksi kulit. Obat ini bekerja dengan menghambat pertumbuhan bakteri penyebab infeksi.',
  },
  {
    'judul': 'Betadine Antiseptic Solution',
    'harga': 'Rp 21.000',
    'foto': 'assets/images/betadine.webp',
    'kategori': 'Bebas',
    'deskripsi': 'Betadine Antiseptic adalah cairan antiseptik luka luar yang mengandung Povidone-Iodine 10%. Digunakan untuk mencegah dan mengobati infeksi pada luka bakar, luka potong, luka gores, dan luka khitan.',
  },
  {
    'judul': 'Cetirizine Dihydrochloride 10mg',
    'harga': 'Rp 9.000',
    'foto': 'assets/images/cetirizine.webp',
    'kategori': 'Bebas',
    'deskripsi': 'Cetirizine adalah obat antihistamin generasi kedua yang efektif meredakan gejala alergi seperti bersin-bersin, hidung gatal/berair, mata berair, dan gatal kulit karena biduran tanpa menyebabkan rasa kantuk berat.',
  },
  {
    'judul': 'Enervon C Multivitamin',
    'harga': 'Rp 35.000',
    'foto': 'assets/images/enervon_c.webp',
    'kategori': 'Vitamin',
    'deskripsi': 'Enervon-C adalah suplemen multivitamin harian yang mengandung kombinasi Vitamin C dan Vitamin B Kompleks. Sangat efektif untuk membantu menjaga daya tahan tubuh, meningkatkan metabolisme, serta memulihkan kondisi tubuh setelah sakit.',
  },
  {
    'judul': 'Ibuprofen 400mg',
    'harga': 'Rp 11.500',
    'foto': 'assets/images/ibuprofen.webp',
    'kategori': 'Pereda Nyeri',
    'deskripsi': 'Ibuprofen adalah obat antiinflamasi nonsteroid (OAINS) yang berkhasiat meredakan rasa sakit derajat ringan hingga sedang, seperti sakit kepala, sakit gigi, nyeri haid, nyeri otot, serta meredakan demam dan peradangan.',
  },
  {
    'judul': 'Paracetamol 500mg',
    'harga': 'Rp 8.000',
    'foto': 'assets/images/paracetamol.webp',
    'kategori': 'Pereda Nyeri',
    'deskripsi': 'Paracetamol adalah obat analgesik (pereda nyeri) dan antipiretik (penurun demam) yang aman digunakan untuk meredakan sakit kepala, sakit gigi, nyeri otot ringan, serta menurunkan suhu tubuh saat demam.',
  },
  {
    'judul': 'Salbutamol Inhaler 100mcg',
    'harga': 'Rp 65.000',
    'foto': 'assets/images/salbutamol.webp',
    'kategori': 'Resep',
    'deskripsi': 'Salbutamol Inhaler adalah obat bronkodilator kerja cepat untuk meredakan serangan sesak napas pada penderita asma atau penyakit paru obstruktif kronis (PPOK). Bekerja dengan melebarkan saluran pernapasan agar udara mengalir lancar.',
  },
  {
    'judul': 'Sangobion Kapsul',
    'harga': 'Rp 18.000',
    'foto': 'assets/images/sangobion.webp',
    'kategori': 'Vitamin',
    'deskripsi': 'Sangobion adalah suplemen zat besi dan vitamin penambah darah yang diformulasikan khusus untuk mengatasi anemia akibat kekurangan zat besi. Membantu pembentukan sel darah merah dan memulihkan vitalitas tubuh.',
  },
  {
    'judul': 'Tolak Angin Cair',
    'harga': 'Rp 24.500',
    'foto': 'assets/images/tolak_angin.webp',
    'kategori': 'Herbal',
    'deskripsi': 'Tolak Angin Cair adalah obat herbal terstandar yang diformulasikan dari ekstrak bahan alami berkhasiat untuk mengatasi gejala masuk angin, perut kembung, mual, pegal-pegal, meriang, dan kelelahan perjalanan.',
  },
];
